#!/usr/bin/env python

import time, argparse
import RPi.GPIO as GPIO

parser = argparse.ArgumentParser()
parser.add_argument('--zone', type=str)
parser.add_argument('--time', type=int)

args = parser.parse_args()
zone = args.zone
duration = args.time * int('60')

pin_list = [38,40]

#grass = [40]
#plants = [38]

GPIO.setmode(GPIO.BOARD)

for pin in pin_list:
    GPIO.setup(pin, GPIO.OUT)

def trigger_grass(mode=GPIO.LOW, delay=0):
    start = time.time()
    print 'Watering that grass for you....'
    GPIO.output(38, mode)
    time.sleep(delay)
    end = time.time()
    print 'Hopefully that grass has been waterd....'
    duration = (end - start)
    print duration, " seconds of watering"
    GPIO.output(38, GPIO.LOW)
    GPIO.cleanup()

def trigger_plants(mode=GPIO.LOW, delay=0):
    start = time.time()
    print 'Watering those plants for you....'
    GPIO.output(40, mode)
    time.sleep(delay)
    end = time.time()
    print 'Hopefully those plants have been waterd....'
    duration = (end - start)
    print duration, " seconds of watering"
    GPIO.output(40, GPIO.LOW)
    GPIO.cleanup()

def trigger():
    if args.zone == 'grass':
	    trigger_grass(mode=GPIO.HIGH, delay=duration)
    elif args.zone == 'plants':
	    trigger_plants(mode=GPIO.HIGH, delay=duration)
    else:
	    print 'Not something I understand'

time.sleep(1)
trigger()
